const Constants = {
    TODO_NAVIGATE: 'TODO_NAVIGATE',
    TODO_FETCHING: 'TODO_FETCHING',
    TODO_FETCHED: 'TODO_FETCHED',
    TODO_FETCHING_ONE: 'TODO_FETCHING_ONE',
    TODO_FETCHED_ONE: 'TODO_FETCHED_ONE',
    TODO_DELETING: 'TODO_DELETING',
    
    APP_NAVIGATE: 'APP_NAVIGATE'
};

export default Constants;